### ISSUE TITLE
Make width seamless and implement scale 

### ISSUE THREAD

**Issue by FlemmingH** [isohedral/tactile-js#1]
Hi

I really love your work and plan to use it for a painting project.

But i got a problem with the breaking of the seamless pattern in the width. In the height it fits perfectly, so i think there's some setting for that?

Secondly. Can you guide me in how to implement a kind of scale that maintain the seamless properties?

**Comment by FlemmingH** [comment]
It's ok, i found a solution. 
Just filter horizontal tiles and vertical tiles from the center tile using a calculated center position.
And then use the left, right, top and (bottom+1) tile's center position as bounding box.

**Comment by isohedral** [comment]
I'm not sure I understand your request. Are you talking about the spiral tiling viewer, specifically the standard (Euclidean) video shown in the lower-left quadrant of the window? By design, that window shows a slice that aligns perfectly in the vertical direction, because that's the portion of the tiling that gets wrapped into a circle to create the spiral on the right. But there's no such restriction for the width of the tiling—in principle, the spiral tiling on the right could show infinitely many tiles, meaning that the Euclidean view is infinitely wide, at least conceptually.

On the other hand, if you've found a solution, then I'm happy, and I'll marked this issue as closed. I welcome additional feature requests if you've got them—I'm hoping to publish an update by the end of the year.

By the way, if you're not working with the spiral view at all, you may find it easier to play with this other interface instead: http://tactile.isohedral.ca.

**Comment by FlemmingH** [comment]
Thanks for your response! Actually i didn't completely solve the problem.

I want to be able to output a cropped seamless tile that i can make some further work on.

Here you see my resent result. It's almost completely seamless but only works if the tiles are completely aligned. So IH07 is impossible with this approach. 

For fun i used Paper.js with path.smooth()...

![tiling](https://user-images.githubusercontent.com/5783466/67270888-cef80a80-f4b9-11e9-9f87-4c33c1563d1b.png)

**Comment by isohedral** [comment]
Nice experiment with path smoothing.  In general you can't simply smooth out the entire tile boundary and expect tiles to continue to assemble seamlessly—there are points where multiple tiles meet which **cannot** be moved. In theory you'd need to smooth out the individual segments that make up a tile's boundary, and then assemble those smoothed segments to make the tile. That can definitely be done, but it involves a bit more low-level work inside the Javascript code.

As for outputting a cropped tile, the problem is that a rectangular tile might not even exist. At best, you can always construct a cropped **parallelogram** that tiles seamlessly. I'll think about adding that as a feature; the trick is to add it without packing too many buttons and menus into the user interface.
